language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_script:
  - sudo aptitude -y -q install ffmpeg libavcodec-extra-53 lame libmp3lame0

install:
  - python setup.py install

script:
  - ydl-binaries -yf -l "binaries/"
